### ISSUE TITLE
PA Review: Projects/Project Page

### ISSUE THREAD

**Issue by rickgorman** [rickgorman/agile-manager#8]

**Comment by rickgorman** [comment]
Hi Ali. Please give this MVP a walk-through. I've got one known issue: the "dropdown->create project" action does not work from the /projects/:id/settings route. Aside from that, I'm interested to see what you find. Thanks!

**Comment by AM-Harris** [comment]
- [ ] If I try to click project list from the home page and I'm not logged in, the app breaks.

**Comment by AM-Harris** [comment]
looks good so far

**Comment by AM-Harris** [comment]
- [ ] A working project show page is included in this mvp

**Comment by rickgorman** [comment]
Added blank/styled show page.

**Comment by rickgorman** [comment]
Added ProtectedRoute handling for the /projects route. Ready for another review!

**Comment by rickgorman** [comment]
heroku is 500ing. standby...

**Comment by rickgorman** [comment]
Ok. Loose ends tied up. Please give this another look-over.

**Comment by AM-Harris** [comment]
Looks good to me!

**Comment by rickgorman** [comment]
Woo hoo!
